# Generated by Django 5.0.14 on 2026-04-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'directorio_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Starter $299/mes'), ('pro', 'Pro $799/mes'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('score_completitud', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_principal', to='directorio.categoria')),
                ('categorias', models.ManyToManyField(blank=True, related_name='empresas', to='directorio.categoria')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Empresa / Perfil',
                'verbose_name_plural': 'Empresas / Perfiles',
                'db_table': 'directorio_empresa_perfil',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa_compradora', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField()),
                ('status', models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('respondida', 'Respondida'), ('archivada', 'Archivada')], default='nueva', max_length=20)),
                ('oculto_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='directorio.empresaperfil')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'db_table': 'directorio_solicitud_cotizacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320)),
                ('descripcion', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('orden', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='directorio.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'directorio_subcategoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresaperfil',
            name='subcategorias',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='directorio.subcategoria'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='uniq_subcategoria_cat_slug'),
        ),
    ]
