# Generated by Django 5.0.14 on 2026-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
