# Generated by Django 5.0.14 on 2026-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_add_invitacion_empresa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['nombre'], name='subcategoria_nombre_idx'),
        ),
    ]
