# Generated by Django 5.0.14 on 2026-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_add_subcategoria_nombre_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaperfil',
            name='csf_documento',
            field=models.FileField(blank=True, null=True, upload_to='csf/'),
        ),
        migrations.AddField(
            model_name='empresaperfil',
            name='csf_status',
            field=models.CharField(choices=[('sin_enviar', 'Sin enviar'), ('pendiente', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='sin_enviar', max_length=20),
        ),
    ]
