# Generated by Django 5.0.14 on 2026-04-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0010_add_blog_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('autor_nombre', models.CharField(max_length=150)),
                ('autor_email', models.EmailField(blank=True, max_length=254)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('moderacion_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foro_posts_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foro_posts', to='directorio.empresaperfil')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foro_posts', to='directorio.subcategoria')),
            ],
            options={
                'verbose_name': 'Foro Post',
                'verbose_name_plural': 'Foro Posts',
                'db_table': 'directorio_foro_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('autor_nombre', models.CharField(max_length=150)),
                ('autor_email', models.EmailField(blank=True, max_length=254)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foro_respuestas_deleted', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foro_respuestas', to='directorio.empresaperfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='directorio.foropost')),
            ],
            options={
                'verbose_name': 'Foro Respuesta',
                'verbose_name_plural': 'Foro Respuestas',
                'db_table': 'directorio_foro_respuesta',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_foro', to='directorio.empresaperfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.foropost')),
            ],
            options={
                'verbose_name': 'Notificacion Foro',
                'verbose_name_plural': 'Notificaciones Foro',
                'db_table': 'directorio_notificacion_foro',
            },
        ),
        migrations.AddIndex(
            model_name='foropost',
            index=models.Index(fields=['subcategoria', '-created_at'], name='directorio__subcate_00ea2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacionforo',
            unique_together={('empresa', 'post')},
        ),
    ]
