# Generated by Django 5.0.14 on 2026-04-17 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0011_add_forum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='foropost',
            name='directorio__subcate_00ea2a_idx',
        ),
        migrations.RemoveField(
            model_name='foropost',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='foropost',
            name='subcategorias',
            field=models.ManyToManyField(related_name='foro_posts', to='directorio.subcategoria'),
        ),
        migrations.AddIndex(
            model_name='foropost',
            index=models.Index(fields=['-created_at'], name='directorio__created_e6eebb_idx'),
        ),
    ]
