# Generated by Django 5.0.14 on 2026-04-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('', 'Cliente'), ('staff', 'Empleado'), ('admin', 'Administrador'), ('owner', 'Propietario Directorio')], db_index=True, default='', max_length=10),
        ),
    ]
